import * as XLSX from 'xlsx';
import type { Response, Event, AnalysisResult } from '../types';

// ============================================
// EXCEL EXPORT
// ============================================

export function exportToExcel(
  event: Event,
  responses: any[]
): void {
  // Prepare data for Excel
  const excelData = responses.map((response) => ({
    'Question': response.questions?.question_text || 'N/A',
    'Response': response.answer_text || response.answer_audio_url || 'N/A',
    'Response Type': response.response_type,
    'Responder Name': response.responder_name || 'Anonymous',
    'Responder Email': response.responder_email || 'N/A',
    'Timestamp': new Date(response.created_at).toLocaleString()
  }));

  // Create workbook and worksheet
  const worksheet = XLSX.utils.json_to_sheet(excelData);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Responses');

  // Set column widths
  worksheet['!cols'] = [
    { wch: 50 }, // Question
    { wch: 50 }, // Response
    { wch: 15 }, // Response Type
    { wch: 25 }, // Responder Name
    { wch: 30 }, // Responder Email
    { wch: 20 }  // Timestamp
  ];

  // Generate filename
  const filename = `${event.slug}_responses_${new Date().toISOString().split('T')[0]}.xlsx`;

  // Download file
  XLSX.writeFile(workbook, filename);
}

// ============================================
// MARKDOWN EXPORT
// ============================================

export function exportToMarkdown(
  event: Event,
  analysis: AnalysisResult
): void {
  const markdown = generateMarkdownReport(event, analysis);
  
  // Create blob and download
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${event.slug}_analysis_${new Date().toISOString().split('T')[0]}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function generateMarkdownReport(
  event: Event,
  analysis: AnalysisResult
): string {
  const date = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  return `# Survey Analysis Report: ${event.title}

**Generated:** ${date}  
**Event:** ${event.title}  
**Status:** ${event.status}

---

## Executive Summary

${analysis.executiveSummary}

---

## Key Themes

${analysis.themes.map((theme, index) => `
### ${index + 1}. ${theme.name}

${theme.description}

${theme.evidenceCount ? `**Evidence Count:** ${theme.evidenceCount} responses` : ''}
`).join('\n')}

---

## Use Cases Identified

${analysis.useCases.map((useCase, index) => `
### ${index + 1}. ${useCase.title}

${useCase.description}

${useCase.priority ? `**Priority:** ${useCase.priority}` : ''}
`).join('\n')}

---

## Recommendations

${analysis.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}

---

## Methodology

This analysis was generated using AI-powered natural language processing to identify patterns, themes, and insights from survey responses. The analysis considers:

- Response frequency and patterns
- Sentiment and tone analysis
- Common themes and topics
- Actionable insights and recommendations

---

*Report generated by Survey4U - AI-Powered Survey Analysis Platform*
`;
}

// ============================================
// QR CODE GENERATION
// ============================================

export function generateQRCodeURL(slug: string): string {
  const surveyURL = `${window.location.origin}/${slug}`;
  // Using a free QR code API
  return `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(surveyURL)}`;
}
