import * as XLSX from 'xlsx';
import type { Response, Event, AnalysisResult } from '../types';

// ============================================
// EXCEL EXPORT
// ============================================

export function exportToExcel(
  event: Event,
  groupedResponses: any[]
): void {
  // Get all unique questions from the first response (assuming all have same questions)
  const questions = groupedResponses.length > 0 
    ? groupedResponses[0].answers.map((a: any) => a.question_text)
    : [];

  // Prepare data for Excel - one row per responder
  const excelData = groupedResponses.map((group) => {
    const row: any = {
      'Name': group.responder_name || 'Anonymous',
      'Email': group.responder_email || 'N/A',
    };

    // Add each answer as a column (Q1, Q2, Q3, etc.)
    group.answers.forEach((answer: any, index: number) => {
      const columnName = `Q${index + 1}: ${answer.question_text}`;
      row[columnName] = answer.answer_text || answer.answer_audio_url || 'No answer';
    });

    row['Submitted At'] = new Date(group.created_at).toLocaleString();

    return row;
  });

  // Create workbook and worksheet
  const worksheet = XLSX.utils.json_to_sheet(excelData);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Responses');

  // Set column widths dynamically
  const colWidths = [
    { wch: 25 }, // Name
    { wch: 30 }, // Email
    ...questions.map(() => ({ wch: 40 })), // Each question column
    { wch: 20 }  // Timestamp
  ];
  worksheet['!cols'] = colWidths;

  // Generate filename
  const filename = `${event.slug}_responses_${new Date().toISOString().split('T')[0]}.xlsx`;

  // Download file
  XLSX.writeFile(workbook, filename);
}

// ============================================
// MARKDOWN EXPORT
// ============================================

export function exportToMarkdown(
  event: Event,
  analysis: AnalysisResult,
  groupedResponses: any[]
): void {
  const markdown = generateMarkdownReport(event, analysis, groupedResponses);
  
  // Create blob and download
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${event.slug}_analysis_${new Date().toISOString().split('T')[0]}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function generateMarkdownReport(
  event: Event,
  analysis: AnalysisResult,
  groupedResponses: any[]
): string {
  const date = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  // Get all questions from first response
  const questions = groupedResponses.length > 0 
    ? groupedResponses[0].answers.map((a: any) => a.question_text)
    : [];

  // Generate responses section
  const responsesSection = groupedResponses.map((group, index) => {
    const answersText = group.answers.map((answer: any, qIndex: number) => 
      `**Q${qIndex + 1}: ${answer.question_text}**\n${answer.answer_text || answer.answer_audio_url || 'No answer'}`
    ).join('\n\n');

    return `### Response ${index + 1}: ${group.responder_name || 'Anonymous'}

**Email:** ${group.responder_email || 'N/A'}  
**Submitted:** ${new Date(group.created_at).toLocaleString()}

${answersText}
`;
  }).join('\n\n---\n\n');

  return `# Survey Analysis Report: ${event.title}

**Generated:** ${date}  
**Event:** ${event.title}  
**Status:** ${event.status}  
**Total Responses:** ${groupedResponses.length}

---

## Executive Summary

${analysis.executiveSummary}

---

## Key Themes

${analysis.themes.map((theme, index) => `
### ${index + 1}. ${theme.name}

${theme.description}

${theme.evidenceCount ? `**Evidence Count:** ${theme.evidenceCount} responses` : ''}
`).join('\n')}

---

## Use Cases Identified

${analysis.useCases.map((useCase, index) => `
### ${index + 1}. ${useCase.title}

${useCase.description}

${useCase.priority ? `**Priority:** ${useCase.priority}` : ''}
`).join('\n')}

---

## Recommendations

${analysis.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}

---

## Survey Questions

${questions.map((q, index) => `${index + 1}. ${q}`).join('\n')}

---

## All User Responses

${responsesSection}

---

## Methodology

This analysis was generated using AI-powered natural language processing to identify patterns, themes, and insights from survey responses. The analysis considers:

- Response frequency and patterns
- Sentiment and tone analysis
- Common themes and topics
- Actionable insights and recommendations

---

*Report generated by Survey4U - AI-Powered Survey Analysis Platform*
`;
}

// ============================================
// QR CODE GENERATION
// ============================================

export function generateQRCodeURL(slug: string): string {
  const surveyURL = `${window.location.origin}/${slug}`;
  // Using a free QR code API
  return `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(surveyURL)}`;
}
